/// Flutter icons Yodel
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Yodel
///      fonts:
///       - asset: fonts/Yodel.ttf
///
///
///
import 'package:flutter/widgets.dart';

class YodelIcons {
  YodelIcons._();

  static const _kFontFam = 'Yodel';

  static const IconData add = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData contacts =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData minus = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData moreactions =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData tick = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData sites = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData manage = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData myshifts =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData notifications =
      const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData profile = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData refresh = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData password_lock =
      const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData update_photo =
      const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData contact_sms =
      const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData contact_call =
      const IconData(0xe80e, fontFamily: _kFontFam);
}
